# Generated by Django 4.1.7 on 2023-06-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image'),
        ('store', '0004_sliderimage'),
    ]

    operations = [
    ]
