# Generated by Django 4.1.7 on 2023-07-02 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230626_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='guest_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.guest'),
        ),
    ]
