# Generated by Django 4.1.7 on 2023-07-02 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_cartitem_guest_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='guest_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.guest'),
        ),
    ]
