# Generated by Django 3.2.19 on 2023-07-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20230705_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='total',
        ),
    ]
