# Generated by Django 3.2.19 on 2023-07-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20230705_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
