# Generated by Django 3.2.19 on 2023-07-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_product_chosen_cartitem_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Принят', 'Принят'), ('В сборке', 'В сборке'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен'), ('Закрыт', 'Закрыт')], max_length=255, null=True),
        ),
    ]
