# Generated by Django 4.1.7 on 2023-08-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
